on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checking out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: preparing building
        run: cmake -H. -B_build -DBUILD_TESTS=ON
      - name: building
        run: cmake --build _build
      - name: upload artifacts
        uses: actions/upload-artifact@v4    
        with:
          name: build
          path: _build/  
          retention-days: 1
      
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checking out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: _build/  
          retention-days: 1
      - name: test
        run: |
          chmod +x _build/factorTest
          _build/factorTest
  
  sources_and_release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checking out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: _build/  
          retention-days: 1
      - name: create deb files
        run: |
          cd _build/ 
          _build/factorTest
          mkdir _artifacts
          cpack -G "DEB"
          mv *.deb _artifacts
