on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checking out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: preparing building
        run: cmake -H. -B_build -DBUILD_TESTS=ON
      - name: building
        run: cmake --build _build
      - name: upload artifacts
        uses: actions/upload-artifact@v4    
        with:
          name: build
          path: _build/  
          retention-days: 1
      
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checking out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: _build/  
          retention-days: 1
      - name: test
        run: |
          chmod +x _build/factorTest
          _build/factorTest
  
  sources_and_release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checking out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: _build/  
          retention-days: 1
      - name: create deb files
        run: |
          cd _build/ 
          mkdir _artifacts
          cpack -G "DEB"
          mv *.deb _artifacts
      
      - name: get version
        run: |
          version=`grep -P ".*_VERSION_.* \d" CMakeLists.txt |  sed 's/.*set(.*\(.\).\{1\}$/\1/' | sed -z 's/\n/./g' | sed 's/.$//'`
          echo "Version=$version" >> $GITHUB_ENV
 
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.Version }}
          name: Release v${{ env.Version }}
          body: "Automated release with built library and source code."
          files: |
            _build/_artifacts/*
          draft: false
          prerelease: false
