on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checking out repository
        uses: actions/checkout@v4
      
      - name: preparing building
        run: cmake -H. -B_build -DBUILD_TESTS
      - name: building
        run: cmake --build _build
      - name: upload artifacts
        uses: actions/upload-artifact@v4    
        with:
          name: build
          path: _build/  
          retention-days: 1
      
  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: checking out repository
        uses: actions/checkout@v4
      
      - name: getting files
        run: cmake -H. -B_build -DBUILD_TESTS

      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: _build/  
          retention-days: 1
      - name: test
        run: |
          chmod +x _build/factorTest
          _build/factorTest
      
